spring.application.name=NotificationService
server.port=0

# MICROMETER OBSERVABILITY CONFIG
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# All traces should be sent to latency analysis tool
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=prometheus

# For Exemplars to work we need histogram buckets
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# EUREKA CONFIG
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka


# KAFKA CONFIG
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notificationId
# Set default topic template
spring.kafka.template.default-topic=notificationTopic
# Set spring serializer to serialize key-value pair(key[String])
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Set spring serializer to serialize key-value pair(object[Java Object])
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Json type mapping(event is random token value)
spring.kafka.consumer.properties.spring.json.type.mapping=event:com.ShoppingApp.NotificationService.OrderPlacedEvent