spring.application.name=ApiGateway
server.port=8080

# EUREKA CONFIG
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# increase logging level of the Api gateway application
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE


# PRODUCT SERVICE ROUTE
# whenever we receive a request with a Path predicate as /api/product
# it will route it to lb://ProductService
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://ProductService
spring.cloud.gateway.routes[0].predicates[0]=Path="/api/product"

# Enable service discovery for route mapping
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ORDER SERVICE ROUTE
# whenever we receive a request with a Path predicate as /api/order
# it will route it to lb://OrderService
spring.cloud.gateway.routes[1].id=OrderService
spring.cloud.gateway.routes[1].uri=lb://OrderService
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order


# INVENTORY SERVICE ROUTE
# whenever we receive a request with a Path predicate as /api/inventory
# it will route it to lb://InventoryService
spring.cloud.gateway.routes[2].id=InventoryService
spring.cloud.gateway.routes[2].uri=lb://InventoryService
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inventory


