eureka.instance.hostname=localhost

# DISABLE SELF REGISTRATION
# eureka shouldn't register itself as client as this(eureka) is a server,
# we don't need to fetch the registry of the server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

server.port=8761