eureka.instance.hostname=localhost

# DISABLE SELF REGISTRATION
# eureka shouldn't register itself as client as this(eureka) is a server,
# we don't need to fetch the registry of the server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

server.port=8761

# MICROMETER OBSERVABILITY CONFIG
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# All traces should be sent to latency analysis tool
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=prometheus

# For Exemplars to work we need histogram buckets
management.metrics.distribution.percentiles-histogram.http.server.requests=true
