spring.application.name=ProductService

server.port=5050

# MONGODB Configuration (matches your Docker Compose)
spring.data.mongodb.uri=mongodb://sourcec:source@127.0.0.1:27017/product-service?authSource=admin
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=product-service
spring.data.mongodb.username=sourcec
spring.data.mongodb.password=source
# spring.data.mongodb.authentication-database=admin  # Required for root user